mst:
    resource: "@MSTBundle/Resources/config/routing.yml"
    prefix:   /api/

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
